export const TIMING = {
  DEBOUNCE_MS: 300,
  SCROLL_DEBOUNCE_MS: 100,
  ANIMATION_DURATION_MS: 1000,
  THROTTLE_MS: 100,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 25,
  SONGS_PER_PAGE: 3,
  LARGE_DATASET_THRESHOLD: 100,
} as const;

export const LAYOUT = {
  HEADER_HEIGHT_PX: 120,
  SIDEBAR_WIDTH_PX: 300,
  MOBILE_BREAKPOINT_PX: 768,
} as const;
